title: EFP Blog
author: byungkichae
email: nchae8@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Economical Freedom Project Blog  
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
url: "https://byungkichae.github.io"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Byungki Chae
  tagline: Developer. Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture
remote_theme: thelehhman/texture
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed